version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: acmecorp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: acmecorp-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/acmecorp
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: acmecorp-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BASE_URL=http://acmecorp-backend:5000
    depends_on:
      - backend

volumes:
  mongo-data:
