version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: acmecorp-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  backend:
    # build:  << for local development
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: mjmacaburas/dashboard-backend:latest
    container_name: acmecorp-backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/acmecorp
    ports:
      - "5000:5000"   # Optional: allows host access to API
    depends_on:
      - mongo

  frontend:
    # build:  << for local deployment
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: mjmacaburas/dashboard-frontend:latest
    container_name: acmecorp-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000   # access backend from host
    ports:
      - "3000:80"   # serves production build via nginx
    depends_on:
      - backend

volumes:
  mongo-data:
