---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - python3-pip
      - nodejs
      - npm
    state: present
  become: yes
  
