---
- name: Cleanup local prod environment
  hosts: local
  become: yes

  tasks:
# ----- Local cleanup (testing) -----
    - name: Stop and remove containers and volumes
      command: docker-compose -f /home/mjmacaburas/company-dashboard/docker-compose.prod.yml down -v
      ignore_errors: yes
      become: no

    - name: Remove unused Docker images
      command: docker image prune -af
      ignore_errors: yes
      become: no

# ----- Remote cleanup on EC2 -----
    # - name: Stop and remove containers and volumes on remote host
    #   docker_compose:
    #     project_src: /home/ubuntu/company-dashboard
    #     files:
    #       - docker-compose.prod.yml
    #     state: absent
    #   become: yes

    # - name: Remove unused Docker images on remote host
    #   command: docker image prune -af
    #   ignore_errors: yes
    #   become: yes
