---
- name: Cleanup local dev environment
  hosts: local
  become: yes

  tasks:
    - name: Stop and remove containers and volumes
      # command: docker-compose -f docker-compose.yml down -v
      # args:
      #   chdir: "{{ playbook_dir }}/.."
      command: docker-compose -f /home/mjmacaburas/company-dashboard/docker-compose.yml down -v
      ignore_errors: yes   # Continue even if containers are already stopped
      become: no

    - name: Remove unused Docker images
      command: docker image prune -af
      ignore_errors: yes   # Continue even if no images to prune
      become: no