---
- name: Deploy local prod containers
  hosts: local   # Change to 'frontend' or 'backend' if targeting separately
  become: yes

  tasks:
# ----- Local deployment (for testing) -----
    - name: Pull latest images from Docker Hub
      command: docker-compose -f /home/mjmacaburas/company-dashboard/docker-compose.prod.yml pull
      become: no

    - name: Start docker-compose services
      command: docker-compose -f /home/mjmacaburas/company-dashboard/docker-compose.prod.yml up -d
      become: no

# ----- Remote deployment on EC2 -----
    # - name: Pull latest images from Docker Hub on remote host
    #   docker_compose:
    #     project_src: /home/ubuntu/company-dashboard
    #     files:
    #       - docker-compose.prod.yml
    #     pull: yes
    #     state: present
    #   become: yes

    # - name: Start docker-compose services on remote host
    #   docker_compose:
    #     project_src: /home/ubuntu/company-dashboard
    #     files:
    #       - docker-compose.prod.yml
    #     state: present
    #     restarted: yes
    #   become: yes